repo: 'list-groups'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-1
  - html
  - css
  - modulifier
  - modulifier-list-group

html:
  - path: 'index.html'
    outline: false
    has:
      - 'ol'
      - 'ol > li'
      - 'ol > li > ul'
      - 'ol > li > ul > li'
      - 'strong'
    search:
      - 'Owls'
      - 'Barn owls'
      - 'Long eared owl'
      - 'Snowy owl'
      - 'Great grey owl'
      - 'Great horned owl'
      - 'Western screech owl'
      - 'Herons'
      - 'Grey heron'
      - 'Great blue heron'
      - 'Night heron'
      - 'Green heron'
      - 'Hawks'
      - 'Broad winged hawk'
      - 'Ferruginous hawk'
      - 'Red tailed hawk'
      - 'Northern harrier'
      - 'Rough legged buzzard'

screenshots:
  - path: 'index.html'
    sizes: [320, 960]
