repo: 'list-groups'
canvasCourse: 'web-dev-2'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 1
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    has:
      - 'link[href="css/modules.css"]'
      - 'ol'
      - 'ol > li'
      - 'ol > li > ul'
      - 'ol > li > ul > li'
      - '.list-group'
      - '.list-group-inline'
      - 'strong'
    search:
      - 'Owls'
      - 'Barn owls'
      - 'Long eared owl'
      - 'Snowy owl'
      - 'Great grey owl'
      - 'Great horned owl'
      - 'Western screech owl'
      - 'Herons'
      - 'Grey heron'
      - 'Great blue heron'
      - 'Night heron'
      - 'Green heron'
      - 'Hawks'
      - 'Broad winged hawk'
      - 'Ferruginous hawk'
      - 'Red tailed hawk'
      - 'Northern harrier'
      - 'Rough legged buzzard'

css:
  - path: 'css/modules.css'
    valid: true
    bestPractices: true
    search:
      - ['https://modulifier.web-dev.tools/#responsive;images;list-group;embed;media-object;icons;hidden;positioning;nice-lists;forms;buttons;accessibility;print', 'Select all the different modules when adding Modulifier.']

screenshots:
  - path: 'index.html'
    sizes: [320, 960]
